[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Netlify Plugin for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js Functions用の設定
[functions]
  external_node_modules = ["@google/generative-ai"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Next.jsのルーティング用のリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
