[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js API Routes用の設定
[[functions]]
  pattern = "api/*"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Next.jsのルーティング用のリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
